---
- name: pre check for windows OS
  hosts: all
  tasks: 
    
    - name: show windows services
      ansible.windows.win_service_info:
      register: service_info 

    - name: print windows services
      ansible.builtin.debug:
        msg: "Service {{ item.display_name }} is {{ item.state }}"
      loop: "{{ service_info.services }}"




  