---
- name: pre check for windows OS
  hosts: all
  tasks: 
    
    - name: show windows services
      ansible.windows.win_service_info:
      register: service_info 

    - name: print windows services that is started
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        msg: "Service {{ item.display_name }} is {{ item.state }}"
        var: service_info.services_started
      loop: "{{ service_info.services }}"






  