---
- name: pre check for windows OS
  hosts: all
  tasks: 
    
    - name: show windows services
      ansible.windows.win_service_info:
      register: service_info 

    - name: print windows services that is started
      ansible.builtin.debug:
        var: service_info.services
        msg: "Service {{ service_info.display_name }} is {{ service_info.state }}"
      when: "'started' in service_info.services | map(attribute='state') | list"
      




  