---
- name: pre check for windows OS
  hosts: all
  tasks: 
    
    - name: show windows services
      ansible.windows.win_service_info:
      register: service_info 

    - name: print windows services that are started
      ansible.builtin.debug:
        msg: "Service {{ item.display_name }} is started"
      loop: "{{ service_info.services }}"
      when: item.state == 'started'

    - name: Retrieve free space on drive C
      community.windows.win_disk_facts:
        filter: volumes
      register: disk_info

    - name: Print free space on drive C
      ansible.builtin.debug:
        msg: "{{ ansible_facts['ansible_disks'] }}"