---
- name: pre check for windows OS
  hosts: all
  tasks: 
    
    - name: show windows services
      ansible.windows.win_service_info:
      register: service_info 

    - name: print windows services that are started
      ansible.builtin.debug:
        msg: "Service {{ item.display_name }} is started"
      loop: "{{ service_info.services }}"
      when: item.state == 'started'

    - name: Get free space on drive c
      community.windows.win_disk_facts:
      register: disk_info

    - name: Print free space on C drive
      ansible.builtin.debug:
        msg: "Free space on C: drive: {{ disk_info.drives['C'].free_bytes | int / 1024 / 1024 / 1024 }} GB"

    - name: Fail if free space is less than 2GB
      ansible.builtin.fail:
        msg: "C: drive has less than 2GB of free space"
      when: disk_info.drives['C'].free_bytes | int < 2 * 1024 * 1024 * 1024  # 2GB in bytes


  