---
- name: pre check for windows OS
  hosts: all
  tasks: 
    
    - name: show windows services
      ansible.windows.win_service_info:
      register: service_info 

    - name: show started services only
      ansible.builtin.set_stats:
        data:
          service_info_running: "{{ service_info.services | selectattr('state', 'equalto', 'started') | map(attribute='display_name') | list }}"

    - name: Retrieve free space on drive C
      community.windows.win_disk_facts:
        filter: volumes
      register: disk_info

    - name: Print free space on drive C
      ansible.builtin.debug:
        msg: "Drive C size available is : {{ ansible_facts.disks[0].partitions[1].volumes[0].size_remaining | int / (1024 ** 3) }} GB."
      failed_when: "( ansible_facts.disks[0].partitions[1].volumes[0].size_remaining | int / (1024 ** 3) ) < 2 "

