---
- name: pre check for windows OS
  hosts: all
  tasks: 

    - name: Search all updates for windows OS
      ansible.windows.win_updates:
        category_names: "*"
        state: searched
      register: wu_result
      ignore_errors: true

    - name: debug wu_result
      ansible.builtin.debug:
        var: wu_result

    - name: print out wu_result KB list
      ansible.builtin.debug:
        msg: "{{ wu_result.updates[item].kb | flatten | list }}"
      loop: "{{ wu_result.updates.keys() }}"

    - name: take virsh snapshot 
      ansible.builtin.command: sudo -i virsh snapshot-create-as --domain windowsaap --name "amy-windowsaapv9"
      delegate_to: main-kvm