---
- name: pre check for windows OS
  hosts: all
  tasks: 

    - name: Search all updates for windows OS
      ansible.windows.win_updates:
        category_names: "*"
        state: searched
      register: wu_result

    - name: Create list of kb in precheck
      ansible.builtin.set_stats:
        data: 
          wu_result_updates: "{{ wu_result.updates | dict2items | map(attribute='value.kb') | list }}" 

