---
- name: pre check for windows OS
  hosts: all
  tasks: 

    - name: Search all updates for windows OS
      ansible.windows.win_updates:
        category_names: "*"
        state: searched
      register: wu_result

    - name: print out wu_result KB list
      ansible.builtin.debug:
        msg: "{{ wu_result.updates }}"

    - name: List only running VMs
      community.libvirt.virt:
        command: list_vms
        state: running
      register: running_vms
