---
- name: pre check for windows OS
  hosts: all
  tasks: 

    - name: Search all updates for windows OS
      ansible.windows.win_updates:
        category_names: "*"
        state: searched
      register: wu_result

    - name: debug wu_result
      ansible.builtin.debug:
        var: wu_result

    - name: print out wu_result KB list
      ansible.builtin.debug:
        msg: "{{ wu_result.updates[item].kb | flatten | list }}"
      loop: "{{ wu_result.updates.keys() }}"

- name: take snapshot 
  hosts: main_kvm
  tasks:

    - name: take virsh snapshot 
      ansible.builtin.command: virsh snapshop-create-as --domain windowsaap --name "amy-windowsaap" 
