---
- name: Take KVM VM Snampshot
  hosts: "{{ NODES }}"
  become: yes
  gather_facts: no


  tasks:
    - name: Take virsh snapshot
      ansible.builtin.shell: "virsh snapshot-create-as --domain {{ kvm_vm_name }} --name {{ snapshot_name }}"
      register: vm_snapshot_result
      delegate_to: windows_snapshot
      ignore_errors: true

    - name: VM snapshot result
      debug:
        var: vm_snapshot_result
