---
- name: Take KVM VM Snapshot
  hosts: main-kvm
  become: yes
  gather_facts: no
  vars:
    ansible_user: '{{ mgd_username }}'
    ansible_become_password: '{{ mgd_password }}'
    ansible_password: '{{ mgd_password }}'

  tasks:
    - name: Take virsh snapshot
      ansible.builtin.shell: "virsh snapshot-create-as --domain {{ windows_domain }} --name {{ windows_name_version }}"
      register: vm_snapshot_result
      ignore_errors: true

    - name: VM snapshot result
      debug:
        var: vm_snapshot_result
