- name: take snapshot 
  hosts: all
  gather_facts: false
  tasks:

    - name: take virsh snapshot 
      ansible.builtin.command: sudo virsh snapshot-create-as --domain {{ windows_domain }} --name {{ windows_name_version }} 
      delegate_to: main-kvm
      register: windows_snapshot
      ignore_errors: true


