---
- name: Start windows patches
  hosts: windows-mgd
  tasks: 
    - name: Run win_updates again
      ansible.windows.win_updates:
        category_names: '*'
        reboot: yes

    - name: Search all updates for windows OS
      ansible.windows.win_updates:
        category_names: "*"
        state: searched
      register: wu_result_after  

    - name: Create list of kb in precheck
      ansible.builtin.set_stats:
        data: 
          wu_result_updates_after: "{{ wu_result_after.updates | dict2items | map(attribute='value.kb') | list }}" 

#get the KB that 