---
- name: Start windows patches
  hosts: all
  tasks: 

    - name: Install updates
      block:
        - name: Run win_updates
          ansible.windows.win_updates:
            category_names: '*'
            reboot: yes
          timeout: 1500
          
      rescue:
        - name: Run win_updates again
          ansible.windows.win_updates:
            category_names: '*'
            reboot: yes

    - name: Search all updates for windows OS
      ansible.windows.win_updates:
        category_names: "*"
        state: searched
      register: wu_result_after

    - name: print out wu_result KB list
      ansible.builtin.set_stats:
        data:
          wu_result_updates_after: "{{ wu_result_after.updates[item].kb | flatten | list }}"
      loop: "{{ wu_result_after.updates.keys() }}"
