---
- name: Do post patching check
  hosts: all
  tasks: 

    - name: show windows services
      ansible.windows.win_service_info:
      register: post_service_info 

    - name: show started services only
      ansible.builtin.set_fact:
        post_service_info_running: "{{ service_info.services | selectattr('state', 'equalto', 'started') | map(attribute='display_name') | list }}"
        
