---
- name: Do post patching check
  hosts: all
  tasks: 

    - name: show windows services
      ansible.windows.win_service_info:
      register: post_service_info 

    - name: show started services only
      ansible.builtin.set_fact:
        post_service_info_running: "{{ post_service_info.services | selectattr('state', 'equalto', 'started') | map(attribute='display_name') | list }}"
        
    - name: show the difference
      ansible.utils.fact_diff:
        before: "{{ service_info_running | ansible.utils.to_paths }}"
        after: "{{ post_service_info_running | ansible.utils.to_paths }}"
