---
- name: Do post patching check
  hosts: all
  tasks: 

    - name: show windows services
      ansible.windows.win_service_info:
      register: post_service_info 

    - name: print windows services that are started
      ansible.builtin.debug:
        msg: "Service {{ item.display_name }} is started"
      loop: "{{ post_service_info.services }}"
      when: item.state == 'started'

    - name: Compare Pre-check services with  post-check services
