---
- name: pre-post file
  hosts: all
  tasks:

#    - name: retrieve windows information
#      ansible.windows.win_service_info:
#      register: pre_post 

    - name: deploy jinja file
      ansible.builtin.template:
        src: post.html.j2
        dest: /home/amysoh/p_p_report.html
      delegate_to: main-kvm