---
- name: pre-post file
  hosts: all
  tasks:

#    - name: retrieve windows information
#      ansible.windows.win_service_info:
#      register: pre_post 

    - name: Get running services of Windows volumes
      ansible.windows.win_service_info:
      register: service_info

    - name: show started services only
      ansible.builtin.set_stats:
        data:
          service_info_running_2: "{{ service_info.services | selectattr('state', 'equalto', 'started') | map(attribute='display_name') | list }}"

    - name: deploy jinja file
      ansible.builtin.template:
        src: post.html.j2
        dest: /home/amysoh/p_p_report.html
      delegate_to: main-kvm